name: Test Windows

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: "Log level"
        required: false
        default: "warning"
        type: choice
        options:
          - error
          - warning
          - info
          - debug

#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
      
jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Repo Code
        run: pip install -e .[dev]

      - name: Run unit tests
        run: python -m pytest --capture=fd .
